baseURL: 'https://arnaudperalta.com'
languageCode: 'en-us'
title: 'Arnaud Peralta'
theme: 'hugo-PaperMod'
paginate: 5

params:
  env: production
  defaultTheme: light
  disableThemeToggle: true
  author: Arnaud Peralta
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  socialIcons:
    - name: github
      url: "https://github.com/arnaudperalta"
    - name: linkedin
      url: "https://www.linkedin.com/in/arnaudperalta"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/9057499/arnaud-peralta"
    - name: email
      url: "mailto:arnaud.peralta@gmail.com"
  profileMode:
    enabled: true
    title: "Software engineer - Integration lover"
    subtitle: "Welcome to my blog."
    imageUrl: "https://avatars.githubusercontent.com/u/34254556?v=4"
    imageTitle: "My face"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Posts
        url: "/post"
      - name: Resume
        url: "/resume.pdf"
  ShowBreadCrumbs: true
