baseURL = 'https://arnaudperalta.github.io'
languageCode = 'en-us'
title = 'Arnaud Peralta'
theme = 'hugo-PaperMod'
paginate = 5000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.social]
  rss            = true
  email          = "arnaud.peralta@gmail.com"
  linkedin       = "https://www.linkedin.com/in/arnaud-peralta-0b5625154/"
  github         = "https://github.com/arnaudperalta"
  stackoverflow  = "https://stackoverflow.com/users/9057499/arnaud-peralta"
